### ISSUE TITLE
Remove retry logic

### ISSUE THREAD

**Issue by maxwofford** [hackclub/innkeeper#1]
Currently the polling runs ever 5 seconds, and if the request fails it keeps retrying every 5 seconds...
https://github.com/dispherical/innkeeper/blob/9ab1ffb5af5a99ab18e15f55b16e98059f4e0d70/index.js#L5

but airtablejs also has retry logic, so we start making multiple retries per call- every 5 seconds. After a minute this could be hundreds of requests. Let's swap out airtablejs with a simple `fetch` call here!

**Comment by dispherical** [comment]
Fixed in 58ed682
